// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkxbarvzewxfxeihxalo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFreGJhcnZ6ZXd4ZnhlaWh4YWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NzY0MDAsImV4cCI6MjA1NzQ1MjQwMH0.VJeHyUhpHtou5ew8hduH3NwX6oSGx8uQww0ixHGRFS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);